import Link from "next/link"

export const metadata = {
    title: 'Denk aan jou',
    description: 'Stuur een denk aan jou lichtje',
}

export default function Page() {
  return <>
    <h1>Welkom bij het denk aan jou lampje</h1>
    <Link href="./patient/home">Patient home</Link> | <Link href="./verwant/lichtje-sturen">Verwant home</Link>
    <div></div>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ultrices finibus velit sed convallis. Fusce sollicitudin lacus a augue lacinia, ac mollis tellus vulputate. Sed nibh erat, pretium sit amet erat non, pellentesque placerat elit. Sed nulla arcu, dignissim ut ligula id, ultricies interdum urna. Quisque eget ante at tortor aliquet malesuada eu eu justo. Etiam sagittis viverra ligula, et varius turpis laoreet sed. Sed quis nisl tempor, laoreet magna vel, varius arcu. Sed id diam consectetur, maximus magna vitae, tristique quam. Nunc porttitor lacus in congue sagittis. Quisque blandit enim sit amet magna condimentum fermentum. Donec metus nisi, mattis id sem et, semper auctor nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras vulputate congue augue eu fringilla. Nam viverra vitae diam dictum bibendum. Aenean sit amet nisl mi.</p>
    <p>Suspendisse potenti. Vestibulum suscipit nisl ac erat commodo, convallis tincidunt eros fringilla. Fusce vel nulla a augue eleifend tempus. Donec mollis tortor erat, ut tristique leo sollicitudin quis. Fusce bibendum euismod libero et tincidunt. Vestibulum nulla massa, fermentum vel eleifend nec, tristique ut arcu. Praesent tempus metus quis neque condimentum pretium. Phasellus ac aliquet tortor, sed consequat sem. Aenean molestie mattis interdum. Quisque sit amet nulla id enim tincidunt finibus. Aliquam dignissim, nisi sit amet mollis lacinia, lectus lectus aliquam magna, et luctus ex massa ac nisi. Nullam tristique volutpat consectetur. Morbi eget condimentum urna, in vulputate dolor.</p>
    <p>Phasellus sit amet justo sit amet urna cursus ullamcorper et quis diam. Nam mattis volutpat ornare. Proin dapibus id leo sit amet dapibus. Integer vitae ullamcorper neque. Praesent lobortis, urna non scelerisque pretium, neque felis auctor lorem, id pharetra magna lacus sit amet arcu. Cras et quam sit amet orci interdum ullamcorper et eget tellus. Etiam aliquet velit eget sem semper pulvinar. Praesent pharetra suscipit dolor. Vivamus fermentum dui elit. Donec at neque eget ante consequat maximus. Maecenas at placerat sem. Donec consequat maximus aliquam. Sed quam enim, porttitor nec sollicitudin non, facilisis id nibh. Pellentesque mollis malesuada nisi, ut vulputate erat consectetur quis.</p>
    <p>In vulputate iaculis velit. In rutrum risus non finibus luctus. Vivamus mi nisi, congue et erat vitae, sodales feugiat urna. Aliquam rhoncus vehicula consequat. Nullam interdum libero eget lorem pellentesque finibus. Donec eget felis nisi. Nam vel commodo mi. Morbi vitae commodo est. Cras eget urna arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis hendrerit libero augue, lobortis consequat massa mollis viverra. Aenean elementum lorem in risus finibus efficitur. Quisque eleifend sed ante eu scelerisque. Nam iaculis turpis quis placerat aliquet. Donec a porttitor dui.</p>
    <p>Aliquam aliquet, felis a ullamcorper eleifend, sapien nunc aliquet nunc, a bibendum metus purus ac orci. Nunc molestie porttitor mollis. Nulla facilisi. Vivamus mollis semper consequat. Etiam vestibulum justo sit amet tempus accumsan. Fusce feugiat neque risus, et vulputate nisl tristique ut. Nullam finibus eros a vehicula viverra. Morbi dignissim ante lorem. Mauris malesuada risus nec lorem aliquet, vitae efficitur leo imperdiet. Praesent dignissim felis velit, vitae tempor tortor convallis at. Cras eu fermentum leo. In sagittis orci quis condimentum efficitur. Sed non nisl id mi porta tincidunt. Nullam id urna vitae erat sodales porta eu accumsan diam.</p>
    <p>In vel sollicitudin ipsum. Donec sit amet nunc nec arcu mollis aliquet. Etiam sed tempus ligula. Vestibulum sodales diam justo, a euismod justo aliquet sed. Sed at sagittis ante. Pellentesque aliquet gravida lorem vel molestie. Curabitur quis pulvinar nisi. Aliquam erat volutpat. Maecenas eu erat tristique, porta ipsum nec, congue risus. Aliquam congue leo pulvinar elementum tincidunt. Donec luctus nec felis sed maximus.</p>
    <p>Curabitur sed suscipit lorem, et mollis sem. Vivamus vitae sem aliquam, pellentesque ipsum scelerisque, suscipit velit. Donec tristique dui eu ullamcorper interdum. Mauris id magna vitae velit sagittis rhoncus ac sed velit. Vivamus vulputate ipsum est, quis convallis nibh auctor ac. Aenean eu lacinia purus, eu dapibus nisl. In ex nulla, feugiat sed enim nec, commodo molestie neque. Vestibulum sem sapien, dictum a velit nec, vulputate molestie arcu. Donec vel mi et augue sodales consectetur. Suspendisse condimentum turpis enim, vitae tristique purus porta id. Praesent tincidunt mauris quis tincidunt tincidunt. Vestibulum tempus ligula imperdiet, luctus arcu eleifend, commodo orci. Curabitur sed commodo velit. Integer condimentum magna ut mauris bibendum, quis finibus tortor auctor. Vestibulum pretium lacus a quam ultrices maximus.</p>
    <p>Cras vulputate faucibus felis vitae accumsan. Aliquam elementum luctus lorem vitae fringilla. Mauris quis risus fringilla neque cursus aliquet eget eu quam. Aenean suscipit quam sit amet nibh porttitor, at finibus nibh sodales. Nam sed ligula quis leo lobortis pharetra vitae non metus. Vivamus auctor accumsan augue a gravida. Sed rutrum egestas neque, eu feugiat tortor sollicitudin vitae. Maecenas faucibus et odio et congue. Duis tincidunt nisl nec justo consectetur malesuada. Nunc consequat sit amet eros non lacinia. Nulla mollis consequat massa a sagittis. Vivamus sed malesuada tellus. Donec condimentum in elit eu eleifend. Etiam ullamcorper, dolor vel blandit aliquam, augue lacus egestas nulla, vel interdum diam tortor ac nibh.</p>
    <p>Nunc sed ligula a tortor tincidunt laoreet in vitae neque. Ut euismod turpis a tempor hendrerit. Etiam mollis placerat nunc. Donec vitae quam aliquam libero eleifend faucibus. Nunc odio nibh, maximus id nunc a, dictum euismod libero. Praesent id facilisis tellus, facilisis congue nisl. Nulla non feugiat sem, quis porttitor eros. Vivamus magna augue, volutpat sit amet elit id, bibendum tincidunt nibh.</p>
    <p>Etiam pretium sollicitudin mi, at placerat nunc ultricies at. Aliquam ac mauris diam. Aliquam bibendum leo varius nulla bibendum maximus. Integer mattis, metus quis accumsan commodo, ipsum erat mollis lectus, et congue eros elit nec ipsum. Aliquam erat volutpat. Aliquam non lectus at quam feugiat accumsan. Integer convallis purus quis arcu condimentum, condimentum sagittis arcu mollis. Ut quis purus vel justo commodo accumsan sed nec urna. Donec at mi sit amet turpis finibus ullamcorper.</p>
  </>
}
